<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
       <title>Adk Recruitment Project</title>
    </head>
    <body>
        <table>
            <thead>
                <tr>
                    <th>Account ID</th>
                    <th>Account Name</th>
                    <th>Revenue</th>
                    <th>Clicks</th>
                </tr>
            </thead>
            <tfoot></tfoot>
            <tbody>
                <!-- Output table rows here -->
                <?php
                    foreach($project_model->models as $model) {
                        ?>
                            <tr>
                                <td><?=$model->getAccountId()?></td>
                                <td><?=$model->getAccountName()?></td>
                                <td><?=$model->getRevenue()?></td>
                                <td><?=$model->getClicks()?></td>
                            </tr>
                        <?php
                    }
                ?>
            </tbody>
        </table>
    </body>
</html> 